### ISSUE TITLE
Assign two variable to the same storage location

### ISSUE THREAD

**Issue by sultanassi95** [facg3/To-do-App#23]
Defining two variables for the same purpose! to_do & n
Line: 56
-------

**Comment by ZooeyMiller** [comment]
To give a little more context to this, it just seems that the use of map is a little confused. I would read over the [Array.map documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) to see if you can refactor your `markTodo` function.

**Comment by walaamedhat** [comment]
done

**Comment by ZooeyMiller** [comment]
@walaamedhat I pulled master but there are no changes?

**Comment by sultanassi95** [comment]
it's cool now :)
good job
