### ISSUE TITLE
createTodoNode TWICE!!!

### ISSUE THREAD

**Issue by sultanassi95** [facg3/To-do-App#26]
There is alot better way to have your sort function work just right.
You have used createTodoNode, and createTodoNode2  functions to make ur sortTodos function work.
which is a long way to do it.
you can do  it using a new creation of UL element. which will work just fine if u knew where to  put it ;)

**Comment by walaamedhat** [comment]
This is a failed way of doing it.

**Comment by sultanassi95** [comment]
maybe u haven't  tried hard enough :p 
so, if u have an if statement inside ur mark button, which tells the li element to move between the first and the second UL elements.
example: if it's in the first
```javascript
if(ul1.hasChildNodes(li)){
ul1.removeChild(li)
ul2.appendChild(li)}
```


just  maybe?
