### ISSUE TITLE
Duplicated create To-do Node function

### ISSUE THREAD

**Issue by aajour** [facg3/To-do-App#29]
I see you have two functions with the same logic  :thinking:

https://github.com/facg3/To-do-App/blob/8cf5f5c6cc47819529d53d26204a9c027fd28092/dom.js#L22

https://github.com/facg3/To-do-App/blob/8cf5f5c6cc47819529d53d26204a9c027fd28092/dom.js#L75

**Comment by walaamedhat** [comment]
The first function is used for div todo element. The second for div done.
