### ISSUE TITLE
Use two functions to update the DOM

### ISSUE THREAD

**Issue by aajour** [facg3/To-do-App#30]
initially  you are provided a function to update the dom 
https://github.com/facg3/To-do-App/blob/8cf5f5c6cc47819529d53d26204a9c027fd28092/dom.js#L153

I see you using the same function, with 2 added to it's name, is there any reason for that? :confounded:
https://github.com/facg3/To-do-App/blob/8cf5f5c6cc47819529d53d26204a9c027fd28092/dom.js#L174

**Comment by walaamedhat** [comment]
The first function is used for div todo element. The second for div done.

close the issues
