### ISSUE TITLE
General Review 

### ISSUE THREAD

**Issue by Alaa-Khattab** [facg3/To-do-App#31]
Good job :+1:  and very nice style , I like it 

but I have some notes : 
- [here](https://github.com/facg3/To-do-App/blob/master/logic.js#L61-#L65) you can return the new array generated by map method instead of store the array in new variable and return it  something like that : 
 ```js
return  to_do.map(function(x) {
      if (x.id ==idToMark) {
        x.done =!x.done;
        return x;
      }else {
       return x;
      }
}
``` 
- its better to use [Array.sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) rather than filter method [here](https://github.com/facg3/To-do-App/blob/master/logic.js#L69).
- [this file](https://github.com/facg3/To-do-App/blob/master/dom.js) is somehow messy and confused me because you use same function twice and I can't recognize why you do that.

**Comment by walaamedhat** [comment]
Thank you 
the two functions are for different purposes but they  have almost the same name : 
- the first one is for "toDo" elements
- the 2nd is for the "done" ones   
Done
